### ISSUE TITLE
Move socket cutout on back of PSU cover

### ISSUE THREAD

**Issue by pboschi** [prusa3d/Prusa-i3-Plus#10]
The socket cutout on the PSU cover should be put on the rear, not on the right side. There's plenty of unused space on the back of the printer when it sits on a desk (due to the heatbed cables), so there's no reason to have the power plug waste additional space on the right.

**Comment by prusa3d-bb** [comment]
Hello

The placement of the power socket was logical based on the soldering work required for the PSUs, a simple change like moving the placement back increases the complexity of the soldering work. It will also increase the production time for all PSUs, and at this time we can't afford to do that.

---

Greyson Haswell
Prusa Research
Prague, Europe
info@prusa3d.com

--- original message ---
On Mon, Nov 21, 2016 at 12:18 am, notifications@github.com pboschi wrote:

The socket cutout on the PSU cover should be put on the rear, not on the right side. There's plenty of unused space on the back of the printer when it sits on a desk (due to the heatbed cables), so there's no reason to have the power plug waste additional space on the right.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by pboschi** [comment]
BTW, here is a little mod to put the power socket on the rear:
http://www.thingiverse.com/make:274708
