### ISSUE TITLE
Y motor holder a bit flimsy

### ISSUE THREAD

**Issue by pboschi** [prusa3d/Prusa-i3-Plus#11]
The Y motor holder is a bit flimsy and bends, reducing tension and misaligning the belt. It should be integrated with the Y-distance part from the start, and come with 3 screw points instead of 2.

**Comment by MartinMajewski** [comment]
Please take a look at my holder design on Thingiverse: http://www.thingiverse.com/thing:1837853

**Comment by pboschi** [comment]
Thanks, i'll try that. The fact is that, depending on material and print quality, the additional bracket alone may or may not reduce the bending of the motor when the belt is finally installed and tightened. If not, you would still need the "Y-distance" part from this repository. With 3 brackets you could now install a damper, but the motor would be coupled to the rest of the printer by that "Y-distance" part, making the damper less effective.

I think that your design, slightly modified to be a bit wider (at least the lower "bracket"), would definitely solve the problem, give the option to install a damper (with full effectiveness), remove the need of additional Y-distance part, and reuse the same screws sizes used for the X motor.

Just look at the X motor bracket... it doesn't bend at all because it has 3 screws AND it's wider.
(X motor mount: ~17mm, 3 screws - Y motor mount: ~10mm, 2 screws).

**Comment by MartinMajewski** [comment]
Please tell me what "Y-distance" part you mean exactly. I have searched the repository but I am not sure what you mean. Is it the 2-point Y-motor holder?

From my experience the 3-point motor holder is absolutely sufficient to hold the motor in position. I have printed it with PLA, three perimeters and 20% honeycomb infill and this is already overkill. But you can always print it sturdier.
The belt should never be that tight, that is bends the motor, anyway. It is absolutely enough if it does not slip over the pulley's teeth when you give it a firm pull. As soon as the motor starts bending (with a dampener or  without), you have tighten the belt too much. This puts unnecessary stress on the motor's shaft.

**Comment by pboschi** [comment]
I'm referring to this part:
https://github.com/prusa3d/Original-Prusa-i3/blob/MK2/Printed-Parts/scad/Y-distance.scad
https://github.com/prusa3d/Original-Prusa-i3/blob/MK2/Printed-Parts/stl/Y-distance.stl

The belt is not over-tightened; but after some days of use i found a bending of the Y motor mount, which in turn causes the belt to slip on a side; that's a very minor problem i know, but with just some more width it would be perfect (but i'll just try with higher infill for now, as you suggested).
![img_20161121_232953](https://cloud.githubusercontent.com/assets/14005124/20503411/b00ce398-b042-11e6-8147-5e91f3d5d24f.jpg)

**Comment by prusa3d-bb** [comment]
Hello, 

It could possibly be resolved by extending the pulley on the shaft a little, so that it better aligns with the y-holder. It might help, while you're reprinting the part.




_________






Greyson Haswell
Prusa Research
Prague, Europe
info@prusa3d.com

--- original message ---
On Mon, Nov 21, 2016 at 11:40 pm, <notifications@github.com> pboschi wrote:

I'm referring to this part:
https://github.com/prusa3d/Original-Prusa-i3/blob/MK2/Printed-Parts/scad/Y-distance.scad
The belt is not over-tightened; but after some days of use i found a bending of the Y motor mount, which in turn causes the belt to slip on a side; that's a very minor problem i know, but with just some more width it would be perfect (but i'll just try with higher infill for now, as you suggested).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by pboschi** [comment]
These two things may help to fix the problem:
http://www.thingiverse.com/thing:1911701
http://www.thingiverse.com/thing:1914857

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
