### ISSUE TITLE
Is this only for MK2 or is the description wrong?

### ISSUE THREAD

**Issue by ghost** [prusa3d/Prusa-i3-Plus#117]
The discription says "Original Prusa i3 MK2", yet most of the content here deals with the MK3.

**Comment by prusa3d-bb** [comment]
Hello,


Can you send me a link please? I'm not sure what are you saying.


Best regards.

—

Alberto López Customer Support
Spanish, English, Portuguese

_______________________________________

PRUSA Research

188/7a Partyzánská, 17000, Prague

+420 222 263 718

+421 220 570 305




Troubleshooting tutorials here!

Follow us on twitter and Facebook! 

Check out our blog!

________________________________________
Please rate our reply ...be generous :-)

--- original message ---
On January 15, 2019, 12:47 PM GMT+1 Spacemarine2018 wrote:


The discription says "Original Prusa i3 MK2", yet most of the content here deals with the MK3.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by ghost** [comment]
This front page "https://github.com/prusa3d/Original-Prusa-i3" says "Original Prusa i3 MK2"

But is this front page really only relevant for the MK2? If not, a change in the discription would be good.

**Comment by Moorviper** [comment]
the mk2 is the default branch

**Comment by prusa3d-bb** [comment]
Hello,


We appreciate the help and feedback from the community, you can report a problem in github and our development team will take a look.


Best regards.

—

Alberto López Customer Support
Spanish, English, Portuguese

_______________________________________

PRUSA Research

188/7a Partyzánská, 17000, Prague

+420 222 263 718

+421 220 570 305




Troubleshooting tutorials here!

Follow us on twitter and Facebook! 

Check out our blog!

________________________________________
Please rate our reply ...be generous :-)

--- original message ---
On January 15, 2019, 9:58 PM GMT+1 Daniel Krah wrote:


the mk2 is the default branch

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by Moorviper** [comment]
there is no problem he has just to read:
https://guides.github.com/activities/hello-world/
and understand what github is and how it works.

**Comment by nathanfjohnson** [comment]
> the mk2 is the default branch

This is the source of @Spacemarine2018's confusion.
