### ISSUE TITLE
MK3S filament sensor question

### ISSUE THREAD

**Issue by ghost** [prusa3d/Prusa-i3-Plus#123]
Can the new indirect sensor detect filament speed (or whether it is moving) or just the presence of filament in the extruder?

**Comment by prusa3d-bb** [comment]
Hello,


The filament sensor will just detect the presence of the filament, the speed is defined by the extruder motor.


Best regards,

—
Marina Curzi
Customer Support 
_______________________________________
PRUSA Research
188/7a Partyzánská, 17000, Prague
+420 222 263 718
+421 220 570 305



Troubleshooting tutorials here!
Follow us on twitter and Facebook! 
Check out our blog!
________________________________________
Please rate our reply ...be generous :-)

--- original message ---
On February 23, 2019, 3:24 PM GMT+1 notifications@github.com wrote:


Can the new indirect sensor detect filament speed (or whether it is moving) or just the presence of filament in the extruder?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---
