### ISSUE TITLE
Hole in LCD Cover for MK2 is to tall

### ISSUE THREAD

**Issue by joseamirandavelez** [prusa3d/Prusa-i3-Plus#149]
The hole for the LCD in the LCD cover for the i3 MK2 is too tall. I had to use the one for the MK2s. It fits perfectly in my MK2. Is that STL for a previous version of the LCD maybe?

https://github.com/prusa3d/Original-Prusa-i3/blob/MK2/Printed-Parts/stl/LCD_cover.stl

**Comment by Prusa-Support** [comment]
Not sure what exactly you mean by a hole being too tall. Do you mean the hole is too deep/long?
I've checked the STL files and the holes for the MK2 version are roughly about 1.1mm deeper than the holes for the MK2S version.
But either version should accommodate an M3x10 screw just fine as they are deeper than 10mm and the LCD panel itself has some thickness as well.

Marek Micek
Prusa Research

**Comment by joseamirandavelez** [comment]
It's been a couple of years. I don't remember exactly, but I think the rectangle height was too tall and I had to use the one for the MK2S.

**Comment by joseamirandavelez** [comment]
I'm not at my computer right now. But it should be easy to check that by importing both STLs in the slicer.

**Comment by Prusa-Support** [comment]
Yes, there are some minor design differences between the models. Most likely because our supplier of the LCD panels might have changed between the MK2 and MK2S versions.
The source files for the models are available so if anyone needs to do any custom changes they are welcome to. We have no plans to update the files in this repository as the MK2/s line of printers is no longer being sold.

Marek Micek
Prusa Research

**Comment by joseamirandavelez** [comment]
So if you aknowledge it's an error (correct file is not found in the Mk2 branch) but you will not fix it, why bother reviving a two year old issue?
