### ISSUE TITLE
LCD cover openscad missing.

### ISSUE THREAD

**Issue by ryanneufeld** [prusa3d/Prusa-i3-Plus#15]
The scad file for the LCD cover appears to be missing from the scad directory.

**Comment by prusa3d-bb** [comment]
Hello Ryan, 

Which files are you referring to?


_________






Greyson Haswell
Prusa Research
Prague, Europe
info@prusa3d.com

--- original message ---
On Wed, Nov 23, 2016 at 06:38 am, <notifications@github.com> Ryan Neufeld wrote:

The scad files appear to be missing from the scad directory.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by ryanneufeld** [comment]
The files for the LCD cover.

**Comment by hede0n** [comment]
I confirm. Missing LCD_cover scad file in MK2 branch

**Comment by ayourk** [comment]
The new Rambo case is also missing.  The STL is there, but the OpenSCAD source is not.

**Comment by ryanneufeld** [comment]
bump

**Comment by ayourk** [comment]
Looks like this has been fixed with the new MK2S update.

**Comment by ryanneufeld** [comment]
Indeed is has been.
