### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ghost** [prusa3d/Prusa-i3-Plus#19]

**Comment by prusa3d-bb** [comment]
Hi there,

I am so sorry that we did not get back to you sooner... It seems like my colleague has unintentionally archived your e-mail :/ Is there still something I could help you with?

Kind regards


—
Tomáš Chvalina
Customer Support


PRUSA Research
+420 222 263 718 
+421 220 570 305
621/8a Prvniho pluku, 18600, Prague
shop.prusa3D.com

--- original message ---
On Tue, Feb 14, 2017 at 02:47 am, <notifications@github.com> 3Delight wrote:

Closed #19.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---
