### ISSUE TITLE
Model of the Injection Molded Spool Holder that comes with the MK3S+

### ISSUE THREAD

**Issue by codysechelski** [prusa3d/Prusa-i3-Plus#194]
I am looking for a model of the Injection Molded (not the printable one, see the photo below) Spool Holder that comes with the MK3S+.  I am not looking to print it, rather, I am designing a part that is meant to interface with it. In particular, with the center support.

I started measuring and molding it, and there is actually quite a bit of nuance in some of the geometry. Depending on the final design, the "ribs" and "voids" in the center support may come into play, so I am looking for something really accurate.

Before I spend the time to measure, model, refine, account for measurement discrepancies, and so on, I want to first find out if the "official" model is available anywhere.

![IMG20230307093346](https://user-images.githubusercontent.com/1571418/223503773-972352e2-580c-4ce5-a613-a4d9f7ec8fd6.jpg)

Thanks!

**Comment by prusa3d-bb** [comment]
Hi Cody,
I was trying to find it, searched through printables, consulted with my colleagues about the model, but this one is just unavailable :(
We're sorry, tried very hard to find anything.
Let me know if we can help you any further.

S pozdravem/ Best regards/ Cordiali saluti


Pavla Šimůnková
Customer Support (cz, it, en)
PRUSA Research | Partyzanska 188/7a | 17000 Prague | CZ 00420 222 263 718 | SK 00421 220 570 305 | ***@***.*** | www.prusa3d.com
—
Your feedback is important to us!


—

Our 24/7 LiveChat help is available in our eshop in the bottom right corner. 



Troubleshooting tutorials here! Follow us on Twitter and Facebook! Check out our Blog! Have a look at our Service guides!

--- original message ---
On March 7, 2023 at 6:40 PM GMT+1 ***@***.*** wrote:



I am looking for a model of the Injection Molded (not the printable one, see the photo below) Spool Holder that comes with the MK3S+. I am not looking to print it, rather, I am designing a part that is meant to interface with it. In particular, with the center support.

I started measuring and molding it, and there is actually quite a bit of nuance in some of the geometry. Depending on the final design, the "ribs" and "voids" in the center support may come into play, so I am looking for something really accurate.

Before I spend the time to measure, model, refine, account for measurement discrepancies, and so on, I want to first find out if the "official" model is available anywhere.


Thanks!

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
--- end of original message ---

**Comment by codysechelski** [comment]
No worries @prusa3d-bb, I appreciate your effort trying to track it down 😀

**Comment by codysechelski** [comment]
@prusa3d-bb Ok, I did my best to model this up on my own. So for any future readers of this issue, you can find it here:
https://www.printables.com/model/418764-unofficial-official-prusa-i3-mk3s-spool-holder-not

**Comment by Prusa-Support** [comment]
Looks accurate indeed.
Very well done and thanks for the update.

Michele Moramarco
Prusa Research
