### ISSUE TITLE
Add Option to prevent Display Auto-Reset

### ISSUE THREAD

**Issue by bardiir** [prusa3d/Prusa-i3-Plus#33]
I'd like to see an option to disable the Display automatically switching back to the info screen after a few seconds or at least an option to increase the timeout.

It's pretty annoying if you're in the move axis menu for example, working on the extruder moving the axis via the menu and the next time you need to move the axis again it's back at the start screen.

**Comment by prusa3d-bb** [comment]
Dear Alexander.

Thank you for your feedback.

There is a single common timeout value for all menus, with the only exception being the live adjust menu, where the timeout is extended. So we can selectively extend the timeout.

What menus do you wish to have the timeout value extended?

Thank you,


—
Vojtěch Bubník

--- original message ---
On Mon, Jul 17, 2017 at 06:18 pm, <notifications@github.com> Alexander Faust wrote:


I'd like to see an option to disable the Display automatically switching back to the info screen after a few seconds or at least an option to increase the timeout.

It's pretty annoying if you're in the move axis menu for example, working on the extruder moving the axis via the menu and the next time you need to move the axis again it's back at the start screen.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by bardiir** [comment]
Where I most definitely noticed it being annoying is the move menus when manually moving any of the axis. Those should in my opinion have very long timeouts as you most likely use them during other maintenance operations.

And overall I think you should increase the timeout by about 50%, it just feels very quick to drop out of the menu again if you look something up in the manual for example while navigating the menu.

Or alternatively an option to disable timeout completely, which I would find pretty useful, sort of advanced users settings.

**Comment by bubnikv** [comment]
I have created a report in the firmware section:
https://github.com/prusa3d/Prusa-Firmware/issues/149
I am closing this issue, please follow the other issue. In the future, please report the firmware issues there.
Thank you.
