### ISSUE TITLE
mk3 repro missing files for mk52 bed and frame dxf

### ISSUE THREAD

**Issue by boelle** [prusa3d/Prusa-i3-Plus#37]
should there not be files for the mk52 bed and the frame dxf files?

**Comment by prusa3d-bb** [comment]
Hello,

These will be available soon.


Best regards,

Jennes De Schutter
Customer Support



PRUSA Research

+420 222 263 718

+421 220 570 305

Partyzánská 188/7a, 17000, Prague

shop.prusa3D.com

--- original message ---
On Mon, Dec 4, 2017 at 01:18 am, <notifications@github.com> Bo Herrmannsen wrote:


should there not be files for the mk52 bed and the frame dxf files?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by boelle** [comment]
@prusa3d-bb also the mk2 repro is missing the frame DXF

**Comment by boelle** [comment]
found the DFX is this PR: https://github.com/prusa3d/Original-Prusa-i3/pull/36

**Comment by akukan** [comment]
Files updated.
