### ISSUE TITLE
MK2 Frame not included

### ISSUE THREAD

**Issue by bwattendorf** [prusa3d/Prusa-i3-Plus#39]
I was wondering what the power supply screw hole sizes and placement are on the MK2 frame? I have an older Prusa frame and was looking to mount the newer power supply.

**Comment by prusa3d-bb** [comment]
Hello,

You can find more info on those over here: http://manual.prusa3d.com/Guide/7.+PSU+%26+Heatbed+assembly/297#s5043


Best regards,

Jennes De Schutter
Customer Support



PRUSA Research

+420 222 263 718

+421 220 570 305

Partyzánská 188/7a, 17000, Prague

shop.prusa3D.com

--- original message ---
On Wed, Dec 6, 2017 at 05:25 pm, <notifications@github.com> bwattendorf wrote:


I was wondering what the power supply screw hole sizes and placement are on the MK2 frame? I have an older Prusa frame and was looking to mount the newer power supply.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by bwattendorf** [comment]
I am looking to know where the holes are on the frame so I can drill holes
on my frame. the holes I am referring to are on step 4 of the guide you
just provided a link to.

**Comment by gregsaun** [comment]
You will find the DXF in MK2S branch here :
https://github.com/prusa3d/Original-Prusa-i3/tree/MK2S/Printed-Parts/scad/FRAME_MK2.dxf

**Comment by bwattendorf** [comment]
Huge Thank you..
