### ISSUE TITLE
extruder cover stuck to extruder

### ISSUE THREAD

**Issue by jltx1** [prusa3d/Prusa-i3-Plus#52]
The back screw, M3x30, for mounting the extruder to the x-carriage will actually bite into the extruder cover.  This is because the distance is only 29mm.  If you try to remove the extruder cover afterwards it takes some force to pry it off and also a challenge to replace.  I modified the cover to include a small divot to accept the tip of the screw without tapping.  But thought you would want to know to correct officially.

**Comment by prusa3d-bb** [comment]
Hello, 

thank you for your feedback, our developers will check the problem and possibly fix it asap. 

Best regards,


Honza Vysušil
Customer Support



PRUSA Research

+420 222 263 718

+421 220 570 305

188/7a Partyzánská, 17000, Prague

shop.prusa3D.com

For simple troubleshooting, please use: http://help.prusa3d.com


Please rate our reply ...be generous :-)

--- original message ---
On Thu, Feb 1, 2018 at 10:37 pm, <notifications@github.com> jltx1 wrote:


The back screw, M3x30, for mounting the extruder to the x-carriage will actually bite into the extruder cover. This is because the distance is only 29mm. If you try to remove the extruder cover afterwards it takes some force to pry it off and also a challenge to replace. I modified the cover to include a small divot to accept the tip of the screw without tapping. But thought you would want to know to correct officially.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---
