### ISSUE TITLE
MK3 extruder idler shaft holes are too tight

### ISSUE THREAD

**Issue by gregsaun** [prusa3d/Prusa-i3-Plus#64]
During the build of my MK2.5 I had the same issue as lot of other users, impossible to put the shaft in.

I suggest to use same technique as pushfit_rod module from x-ends.scad for this hole.

**Comment by prusa3d-bb** [comment]
Hello,

Sorry to hear you are also experiencing the same issue and thanks for your suggestion on the GitHub page.

Have you been able to solve it?


Regards,


—
Blas Palencia
Customer Support

PRUSA Research
+420 222 263 718
+421 220 570 305
188/7a Partyzánská, 17000, Prague
shop.prusa3D.com

Please rate our reply ...be generous :-)

--- original message ---
On Mon, Mar 19, 2018 at 11:32 am, <notifications@github.com> Grégoire Saunier wrote:


During the build of my MK2.5 I had the same issue as lot of other users, impossible to put the shaft in.

I suggest to use same technique as pushfit_rod module from x-ends.scad for this hole.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by gregsaun** [comment]
Yes I use a file to increase hole

**Comment by prusa3d-bb** [comment]
Hello,

Very happy to hear :)

Nice weekend!




—
Blas Palencia
Customer Support

PRUSA Research
+420 222 263 718
+421 220 570 305
188/7a Partyzánská, 17000, Prague
shop.prusa3D.com

Please rate our reply ...be generous :-)

--- original message ---
On Wed, Mar 21, 2018 at 09:44 am, <notifications@github.com> Grégoire Saunier wrote:


Yes I use a file to increase hole

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by gregsaun** [comment]
Hope you will fix this for other users 😉

**Comment by ManuGithubSteam** [comment]
Just to let you know there is a report on the prusa build pages, that after heavy use for two months, this hole in the idler got wider and printing was not possible anymore because the pressure was too low on the filament. So I'm not sure making it wider is a good solution. But I also do not have another good one...

**Comment by prusa3d-bb** [comment]
Hello,

We know about these report but it is only happening to a small quantity of customers.

Please let me know if the issue gets worse and you need our help. You can always try to print a new part.

https://www.prusa3d.com/prusa-i3-printable-parts/

Regards,




—
Blas Palencia
Customer Support

PRUSA Research
+420 222 263 718
+421 220 570 305
188/7a Partyzánská, 17000, Prague
shop.prusa3D.com

Please rate our reply ...be generous :-)

--- original message ---
On Sat, May 5, 2018 at 08:25 am, <notifications@github.com> Manuel wrote:


Just to let you know there is a report on the prusa build pages, that after heavy use for two months, this hole in the idler got wider and printing was not possible anymore because the pressure was too low on the filament. So I'm not sure making it wider is a good solution. But I also do not have another good one...

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by Prusa-Support** [comment]
If you are still having issues with the extruder idler please contact us at info@prusa3d.com.

Marina Curzi
Prusa Research
