### ISSUE TITLE
MK2.5/MK3 hotend is very difficult to remove for maintenance

### ISSUE THREAD

**Issue by gregsaun** [prusa3d/Prusa-i3-Plus#69]
On MK2.5/MK3 extruder, it is very hard to remove hotend if you need to do some maintenance on the PTFE tube (for example). This was much easier on MK2s extruder

**Comment by Panayiotis-git** [comment]
For the MK2, I've split the extruder body in two halves:
![extruder-body](https://user-images.githubusercontent.com/32783577/38456815-605b41e8-3a91-11e8-9b8c-532f988cd5b6.png)
![extruder-body-2](https://user-images.githubusercontent.com/32783577/38456816-63f8d9f0-3a91-11e8-8e12-a240b0aa17ae.png)

May be something similar is possible with the 2.5/3 extruder.

**Comment by matthew-humphrey** [comment]
+1. I literally had to cut the PTFE tube (and unfortunately the retention collet) to get it out.

**Comment by stephanpark** [comment]
There is a trick to it.
1. Tilt the hotend assembly slightly enough to get a spudger between heatsink and Extruder body.
2. Tilt the hotend assembly back down putting the pull force on the wedge.  This keeps the collar parallel and avoids pinch jamming and bending the part that can, the PTFE liner.
3. Lever the wedge while again keeping the hotend assembly parallel as possible slightly bending the PTFE tube into an S-like shape slipping the hotend clear of the capture collar.
If you did it right, it will slip right out without permanently bending PTFE or damaging anything.

You can alternately design the Extruder body's collar with a rotational clearance rather than the simple and ineffective chamfer of the original design but once you try the trick, you will no longer feel the neeed to.

**Comment by Mochanic** [comment]
OMG stephanpark, that worked so well!  I was about to start cutting $*#&  What a stupid design that was... Definitely like the spit design much better!

Where can I download the split housing?  I want to print that as soon as I get my printer back together!

**Comment by amirsamad** [comment]
> There is a trick to it.
> 
> 1. Tilt the hotend assembly slightly enough to get a spudger between heatsink and Extruder body.
> 2. Tilt the hotend assembly back down putting the pull force on the wedge.  This keeps the collar parallel and avoids pinch jamming and bending the part that can, the PTFE liner.
> 3. Lever the wedge while again keeping the hotend assembly parallel as possible slightly bending the PTFE tube into an S-like shape slipping the hotend clear of the capture collar.
>    If you did it right, it will slip right out without permanently bending PTFE or damaging anything.
> 
> You can alternately design the Extruder body's collar with a rotational clearance rather than the simple and ineffective chamfer of the original design but once you try the trick, you will no longer feel the neeed to.

Yes indeed, this works. Took me a while to figure it out, but works!

**Comment by Prusa-Support** [comment]
Hello! Closing this issue as it has been resolved, in the meantime we have better manuals and guides to access hotend and their parts. Sorry for the response on this from my side being only now! 

Alessandro Pantaleo
Prusa Research
