### ISSUE TITLE
Replacing the extruder assembly

### ISSUE THREAD

**Issue by allenfr** [prusa3d/Prusa-i3-Plus#86]
Nice comments and videos for removing a heatsink extruder assembly. That went fine.  I will figure out how to remove the tubing next. Any videos on putting the assembly back in ?  I bought mine assembled, so I feel like a rocket scientist at this point !

**Comment by stahlfabrik** [comment]
Hi, here is all you need https://manual.prusa3d.com

**Comment by prusa3d-bb** [comment]
Hello,


You can check the assembly manuals (https://manual.prusa3d.com/), and the E3D V6 assembly guide (https://e3d-online.dozuki.com/Guide/V6+Assembly/6).


Best regards,


—
Marina Curzi
Customer Support 

PRUSA Research
+420 222 263 718
+421 220 570 305
188/7a Partyzánská, 17000, Prague
shop.prusa3D.com

For simple troubleshooting, please use: http://help.prusa3d.com

Please rate our reply ...be generous :-)

--- original message ---
On Thu, Jul 19, 2018 at 09:22 am, <notifications@github.com> Christoph Stahl wrote:


Hi, here is all you need https://manual.prusa3d.com

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---
