### ISSUE TITLE
No scad files for new Mk3 extruder 

### ISSUE THREAD

**Issue by arafalski** [prusa3d/Prusa-i3-Plus#89]
Where are scad files of new extruder for Mk3 and Mk2.5? :D

**Comment by tracernz** [comment]
Discussion: https://github.com/prusa3d/Original-Prusa-i3/commit/ad994c49ac9211c01122046ce410f98257c35ddf#commitcomment-29741639

**Comment by prusa3d-bb** [comment]
Hello,

the new extruder is not designed in SCAD, unfortunately, so there will be no SCAD files. However, we will publish STEP files for the extruder that can be modified in most design programs. They should be posted to GitHub sometime this week.

Best regards,


Marek Míček

Customer Support


PRUSA Research
+420 222 263 718
+421 220 570 305
188/7a Partyzánská, 17000, Prague
shop.prusa3D.com


For simple troubleshooting, please use: http://help.prusa3d.com

--- original message ---
On Sun, Jul 22, 2018 at 10:02 pm, <notifications@github.com> Michael Corcoran wrote:


Discussion: ad994c4#commitcomment-29741639

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by arafalski** [comment]
It's even better. Thanks :D

**Comment by Olefff** [comment]
STEP files would be awesome please. So fed up of having to convert STL's to STEP's so I can use them.
Thank you :)

**Comment by 3d-gussner** [comment]
@prusa3d-bb any update on the STEP files?

**Comment by stahlfabrik** [comment]
They were just released

**Comment by GMagician** [comment]
Just a question, importing extruder-body step file into onshape will not generate a part, only surfaces. Is it possible that such file is non manifold?

**Comment by lf-** [comment]
@GMagician it's possible (likely?) that onshape is buggy :) I hit a similar non-manifold import bug with SAT files from Revit. But it's confusing because I could have sworn I saw some Prusa Research engineers working in what looked like something which was definitely not Fusion and looked kind of like onshape, so one would expect that it should import correctly.

**Comment by GMagician** [comment]
@lf- all is possible. I imported correctly extruder cover while body gives me only surfaces. Someone else in thingiverse confirmed that is non manifold (and he uses Solidworks)

**Comment by TNDavid** [comment]
I cannot find the step files for the new extruder, where are they?

**Comment by akukan** [comment]
@TNDavid  https://github.com/prusa3d/Original-Prusa-i3/tree/MK3/Printed-Parts/STEP

**Comment by prusa3d-bb** [comment]
Hello,


does that mean you found them?


Regards,

Marek Míček

Customer Support


PRUSA Research
+420 222 263 718
+421 220 570 305
188/7a Partyzánská, 17000, Prague
shop.prusa3D.com


For simple troubleshooting, please use: http://help.prusa3d.com

--- original message ---
On December 15, 2018, 2:23 PM GMT+1 notifications@github.com wrote:


@TNDavid https://github.com/prusa3d/Original-Prusa-i3/tree/MK3/Printed-Parts/STEP

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by TNDavid** [comment]
Yes, found them!
